// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-QzuXKtv-vwFPuim8FNx_quqorCAh8ek',
    appId: '1:128295518308:web:aa6737dc4d63bfa4d15f71',
    messagingSenderId: '128295518308',
    projectId: 'iemcrp-badcd',
    authDomain: 'iemcrp-badcd.firebaseapp.com',
    storageBucket: 'iemcrp-badcd.appspot.com',
    measurementId: 'G-8Y8RNTHZTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc2CnHpW4m6yHnOBEK0WTCh56Q1DvZm-o',
    appId: '1:128295518308:android:a57cd2df52a210f8d15f71',
    messagingSenderId: '128295518308',
    projectId: 'iemcrp-badcd',
    storageBucket: 'iemcrp-badcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwqOxWRfxD_mPjK-rW3L0cAlnFypPd_MI',
    appId: '1:128295518308:ios:4b399966bc8d1109d15f71',
    messagingSenderId: '128295518308',
    projectId: 'iemcrp-badcd',
    storageBucket: 'iemcrp-badcd.appspot.com',
    iosClientId: '128295518308-3u7o1inhpl5loe85qjqfgp2jpq1pld1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.iemcrp2',
  );
}
